default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: luke
  password: password
  host: localhost

development:
  <<: *default
  database: studentGradebook_development

test:
  <<: *default
  database: studentGradebook_test
production:
  <<: *default
  database: studentGradebook_production
  username: studentGradebook
  password: <%= ENV['STUDENTGRADEBOOK_DATABASE_PASSWORD'] %>
